// Mocks generated by Mockito 5.4.5 from annotations
// in src/test/domain/usecases/send_message_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:src/domain/entities/message.dart' as _i4;
import 'package:src/domain/repositories/i_message_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMessageRepository extends _i1.Mock
    implements _i2.IMessageRepository {
  MockIMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendMessage(_i4.Message? message) => (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [message],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i4.Message> getMessages() => (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
        ),
        returnValue: _i3.Stream<_i4.Message>.empty(),
      ) as _i3.Stream<_i4.Message>);

  @override
  _i3.Future<void> saveMessage(_i4.Message? message) => (super.noSuchMethod(
        Invocation.method(
          #saveMessage,
          [message],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
